transcriptome: "workflow/resources/transcriptome/dd_Ptoc_v1.fasta"
rrna_db: "/DATA11900-NFS/projects/ferenc.kagan/Backup-data/rRNA_databases_v4/smr_v4.3_sensitive_db.fasta"
kraken2_db: "/DATA11900-NFS/projects/ferenc.kagan/Backup-data/kraken_plan/"
threads: 50
PE_ext: "_R{pair}_001.fastq.gz"
